/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface FirstComp {
        /**
          * The last name
         */
        "data": string | {[key: string]: {label:string,content:string}};
        /**
          * The first name
         */
        "first": string;
        "handleClick": (id: any) => Promise<void>;
        "handleGetStateClick": () => Promise<void>;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLFirstCompElement extends Components.FirstComp, HTMLStencilElement {
    }
    var HTMLFirstCompElement: {
        prototype: HTMLFirstCompElement;
        new (): HTMLFirstCompElement;
    };
    interface HTMLElementTagNameMap {
        "first-comp": HTMLFirstCompElement;
    }
}
declare namespace LocalJSX {
    interface FirstComp {
        /**
          * The last name
         */
        "data"?: string | {[key: string]: {label:string,content:string}};
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "first-comp": FirstComp;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "first-comp": LocalJSX.FirstComp & JSXBase.HTMLAttributes<HTMLFirstCompElement>;
        }
    }
}
